name: Build LaTeX and Release document
on: 
  push:
    tags:
    - 'v*.*.*'
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: kokebok.tex
          
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: kokebok.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
