name: Build LaTeX and Release document
on: 
  push:
    tags:
    - 'v*.*.*'
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: kokebok.tex
          
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: kokebok.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          # Arguments for the git add command
          add: kokebok.pdf
          # Name of the branch to use, if different from the one that triggered the workflow
          branch: latest
          # The message for the commit
          message: Added latest version!
          #github_token: # optional, default is ${{ github.token }}
