name: Build LaTeX and Release document
on: 
  push:
    tags:
    - 'v*.*.*'
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: kokebok.tex
          
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: kokebok.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push file to latest
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/oyvindskaaden/kokebok target
          cd target
          git switch latest
          cp ../kokebok.pdf ./kokebok.pdf
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic publish of latest version ${{ steps.get_version.outputs.VERSION }}"
          git push origin latest

